name:                decaf-client
version:             0.0.0.1
github:              "teloscube/decaf-client-haskell"
license:             BSD3
author:              "Vehbi Sinan Tunalioglu"
maintainer:          "vst@vsthost.com"
copyright:           "2020 Teloscube Pte Ltd"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            DECAF API Client Suite for Haskell
category:            Web

description:         Please see the README on GitHub at <https://github.com/teloscube/decaf-client-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- base64-bytestring
- http-client
- http-conduit
- http-types
- unordered-containers

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror

executables:
  decaf-client-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - decaf-client

tests:
  decaf-client-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - decaf-client
