name:                decaf-client
version:             0.0.0.3
github:              "teloscube/decaf-client-haskell"
license:             BSD3
author:              "Vehbi Sinan Tunalioglu"
maintainer:          "vst@vsthost.com"
copyright:           "2020-2022 Teloscube Pte Ltd"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            DECAF API Client Suite for Haskell
category:            Web

description:         Please see the README on GitHub at <https://github.com/teloscube/decaf-client-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- base64-bytestring
- bytestring
- case-insensitive
- http-client
- http-conduit
- http-types
- mtl
- network-uri
- text
- unordered-containers

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror
  default-extensions:
  ## GHC 2021 extensions (see https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0380-ghc2021.rst):
  - ConstraintKinds
  - DeriveGeneric
  - ExistentialQuantification
  - FlexibleContexts
  - GeneralizedNewtypeDeriving
  - RankNTypes
  - ScopedTypeVariables
  - TupleSections
  ## Project specific:
  - OverloadedStrings

executables:
  decafcli:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - decaf-client
    - optparse-applicative

  decaf-client-examples-accountinfo-exe:
    main:                Main.hs
    source-dirs:         examples/accountinfo
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - decaf-client

tests:
  decaf-client-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - decaf-client

  decaf-client-doctest:
    main:                doctest.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    dependencies:
    - decaf-client
    - doctest
