name:                decaf-client
version:             0.0.0.4
github:              "teloscube/decaf-client-haskell"
license:             BSD3
author:              "Vehbi Sinan Tunalioglu"
maintainer:          "vst@vsthost.com"
copyright:           "2020-2022 Teloscube Pte Ltd"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            DECAF API Client Suite for Haskell
category:            Web

description:         Please see the README on GitHub at <https://github.com/teloscube/decaf-client-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- base64-bytestring
- bytestring
- case-insensitive
- deriving-aeson
- exceptions
- http-conduit
- http-types
- network-uri
- text
- unordered-containers
- yaml

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wunused-packages
  default-extensions:
  ## Begin: Haskell 2021 Extensions List
  - BangPatterns
  - BinaryLiterals
  - ConstrainedClassMethods
  - ConstraintKinds
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - EmptyCase
  - EmptyDataDeriving
  - ExistentialQuantification
  - ExplicitForAll
  - FlexibleContexts
  - FlexibleInstances
  - GADTSyntax
  - GeneralisedNewtypeDeriving
  - HexFloatLiterals
  - ImportQualifiedPost
  - InstanceSigs
  - KindSignatures
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NamedWildCards
  - NumericUnderscores
  - PolyKinds
  - PostfixOperators
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - StandaloneKindSignatures
  - TupleSections
  - TypeApplications
  - TypeOperators
  - TypeSynonymInstances
  ## End: Haskell 2021 Extensions List
  - OverloadedStrings

executables:
  decafcli:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - decaf-client
    - aeson-combinators
    - brick
    - monad-parallel
    - optparse-applicative
    - unordered-containers
    - vector
    - vty

tests:
  decaf-client-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - decaf-client
    - hspec
    - aeson
    - base64-bytestring
    - bytestring
    - case-insensitive
    - deriving-aeson
    - exceptions
    - http-conduit
    - http-types
    - network-uri
    - text
    - unordered-containers
    - yaml

  decaf-client-doctest:
    main:                doctest.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    dependencies:
    - decaf-client
    - doctest
