name:                decaf-client
version:             0.0.0.6
github:              "teloscube/decaf-client-haskell"
license:             BSD3
author:              "Vehbi Sinan Tunalioglu"
maintainer:          "vst@vsthost.com"
copyright:           "2020-2022 Teloscube Pte Ltd"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            DECAF API Client Suite for Haskell
category:            Web

description:         Please see the README on GitHub at <https://github.com/teloscube/decaf-client-haskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wunused-packages
  dependencies:
  - aeson
  - base64-bytestring
  - bytestring
  - case-insensitive
  - exceptions
  - http-conduit
  - http-types
  - network-uri
  - text
  - yaml

executables:
  decafcli:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -Wunused-packages
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - aeson-combinators
    - blaze-html
    - blaze-markup
    - brick
    - bytestring
    - data-default-class
    - decaf-client
    - exceptions
    - http-types
    - monad-parallel
    - optparse-applicative
    - scotty
    - string-interpolate
    - text
    - vector
    - vty
    - warp
    - yaml

tests:
  decaf-client-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -Wunused-packages
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - bytestring
    - decaf-client
    - exceptions
    - hspec
    - text
    - unordered-containers

  decaf-client-doctest:
    main:                doctest.hs
    source-dirs:         .
    ghc-options:
    - -Wall
    - -Wunused-packages
    - -threaded
    dependencies:
    - doctest
